apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-function
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: APP_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: FUNCTION_TARGET
              value: helloHttp
