apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: hello-service
profiles:
  - name: stg
    manifests:
      helm:
        releases:
          - name: hello-service
            chartPath: chart
            valuesFiles:
              - values/stg.yaml
  - name: prod
    manifests:
      helm:
        releases:
          - name: hello-service
            chartPath: chart
            valuesFiles:
              - values/prod.yaml
deploy:
  cloudrun: {}
